Modify this information as you choose to fit your app.
IMPORTANT: OpenAi API KEY and sql password are necessary to run the script

MRN = '000123456'
last_name = 'patient_last_name'
user_provider = 'provider_user_name'
password_provider = '1234'
user_admin = 'admin_username'
password_admin = '12345'

openai_api_key = ''
sql_password = ''